### ISSUE TITLE
Cannot install boruta_py

### ISSUE THREAD

**Issue by naileakim** [danielhomola/boruta_py#1]
Hello,

I am using python homebrew on my mac, and have some trouble installing boruta_py.
Could you help ?

Thanks !

**Comment by danielhomola** [comment]
Hi,

Sure, but you'll need to be more specific. What's the problem? What error message you get?

**Comment by naileakim** [comment]
I download your github repo and dropped it in /usr/local/lib/python2.7/site-packages
I tried import boruta_py but I got the following error : `ImportError: No module named boruta_py`

**Comment by danielhomola** [comment]
I'm not sure that's supposed to work.. Just clone the repo and put a copy
of boruta_py into the directory you're working in.. Then import boruta_py
should work..

On 17 February 2016 at 14:05, naileakim <notifications@github.com> wrote:

> I download your github repo and dropped it in
> /usr/local/lib/python2.7/site-packages
> I tried import boruta_py but I got the following error : ImportError: No
> module named boruta_py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielhomola/boruta_py/issues/1#issuecomment-185220270>
> .
>



-- 
Daniel Homola

**Comment by kushtehlan** [comment]
i cloned repositery.. pasted in my anaconda/Lib/site-packages

still its not working. Its showing "No module named boruta_py"
