### ISSUE TITLE
Transfer this project to scikit-learn-contrib

### ISSUE THREAD

**Issue by mfeurer** [danielhomola/boruta_py#10]
Hi,

this is not really an 'issue', only a suggestion. You could transfer this project to the [scikit-learn-contrib](https://github.com/scikit-learn-contrib) which is a collection of algorithms compatible with scikit-learn, but not yet in a state where they are merged. This could greatly increase the visibility of your project. What do you think about this?

**Comment by danielhomola** [comment]
Hi,

sorry  for the massively belated answer but I was on annual leave.. This is a great idea, and I'll do it as soon as I have time to write unit tests so it passes the criteria for inclusion.
