### ISSUE TITLE
upload to pypi and anaconda

### ISSUE THREAD

**Issue by Stibbons** [danielhomola/boruta_py#14]
Hello, do you consider uploading this package to pypi and anaconda ?

**Comment by MaxBenChrist** [comment]
👍 

You can also configure a travis to upload it whenever you tag a new release

**Comment by danielhomola** [comment]
Sorry for the long absence. Will try and do this on the coming weekend.

**Comment by MaxBenChrist** [comment]
Nice, if you need some help, tell me. I just recently configured everything for my tsfresh package.

with travis it is quite easy to setup. you only need to setup .travis.yml

**Comment by Stibbons** [comment]
(sorry for self-advertising) As example of a package that self upload to pypi when tagged (or "release created" on github): https://github.com/Stibbons/txrwlock

Don't know if it is also possible to auto publish on anaconda from travis, would be so cool :)

**Comment by danielhomola** [comment]
I finally did this, thanks guys for pushing me :)

**Comment by Saravji** [comment]
As I could not find an anconda instance of this package, I did go ahead and created one:
[https://anaconda.org/saravji/boruta](https://anaconda.org/saravji/boruta)
It's for linux 64 only at this time. And of course I have referenced back to this repo, as the origin of the package.

**Comment by danielhomola** [comment]
thanks a lot @Saravji !
