### ISSUE TITLE
Python3?

### ISSUE THREAD

**Issue by mbernico** [danielhomola/boruta_py#2]
Just started using your code.  I also just started using python 3.5.   Do you have any plans for 3.5 support?  If not I'll give it a shot.

**Comment by danielhomola** [comment]
I wasn't really planning doing that so if you could help with it, that would be awesome :)

**Comment by mbernico** [comment]
Cool, I've forked your code.  I'm testing Py3 now.   I've also added the skeleton for setup tools so it can be installed as a package.   Have you ever considered registering this on pypy?  

Also, seems a bit brittle now.  Know what's going on here? https://github.com/mbernico/boruta_py/blob/master/boruta/examples/iris.ipynb

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-fb0214bdb52e> in <module>()
----> 1 feat_selector.fit(X,y)

/home/mike/dev/boruta_py/boruta/boruta_py2.py in fit(self, X, y)
    169         """
    170 
--> 171         return self._fit(X, y)
    172 
    173     def transform(self, X, weak=False):

/home/mike/dev/boruta_py/boruta/boruta_py2.py in _fit(self, X, y)
    311         else:
    312             # and 2 otherwise
--> 313             ranks = ranks - np.min(ranks) + 2
    314         self.ranking_[not_selected] = ranks
    315 

/home/mike/anaconda/envs/Python2.7/lib/python2.7/site-packages/numpy/core/fromnumeric.pyc in amin(a, axis, out, keepdims)
   2357     else:
   2358         return _methods._amin(a, axis=axis,
-> 2359                               out=out, keepdims=keepdims)
   2360 
   2361 

/home/mike/anaconda/envs/Python2.7/lib/python2.7/site-packages/numpy/core/_methods.pyc in _amin(a, axis, out, keepdims)
     27 
     28 def _amin(a, axis=None, out=None, keepdims=False):
---> 29     return umr_minimum(a, axis, None, out, keepdims)
     30 
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):

ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by danielhomola** [comment]
I'll hope to get it incorporated into scikit learn actually, but distributing it via pypy would be a nice planB.. 
Thanks for adding setup.py and fixing the bug when all features are selected.
