### ISSUE TITLE
Error when all variables are selected

### ISSUE THREAD

**Issue by mbernico** [danielhomola/boruta_py#4]
When all variables are selected, this error will be thrown.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-fb0214bdb52e> in <module>()
----> 1 feat_selector.fit(X,y)

/home/mike/dev/boruta_py/boruta/boruta_py2.py in fit(self, X, y)
    170         """
    171 
--> 172         return self._fit(X, y)
    173 
    174     def transform(self, X, weak=False):

/home/mike/dev/boruta_py/boruta/boruta_py2.py in _fit(self, X, y)
    322         else:
    323             # and 2 otherwise
--> 324             ranks = ranks - np.min(ranks) + 2
    325         self.ranking_[not_selected] = ranks
    326 

/home/mike/anaconda/envs/Python2.7/lib/python2.7/site-packages/numpy/core/fromnumeric.pyc in amin(a, axis, out, keepdims)
   2357     else:
   2358         return _methods._amin(a, axis=axis,
-> 2359                               out=out, keepdims=keepdims)
   2360 
   2361 

/home/mike/anaconda/envs/Python2.7/lib/python2.7/site-packages/numpy/core/_methods.pyc in _amin(a, axis, out, keepdims)
     27 
     28 def _amin(a, axis=None, out=None, keepdims=False):
---> 29     return umr_minimum(a, axis, None, out, keepdims)
     30 
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):

ValueError: zero-size array to reduction operation minimum which has no identity

Debug Example:

selected = [0 1 2 3]
not_selected = []
imp_history_rejected = []
iter_ranks = []
rank_medians = []
ranks = []

(I'll send you a PR with fixes for these, just documenting them here so you know what the PR is doing.)

**Comment by danielhomola** [comment]
Great, thanks!
