### ISSUE TITLE
_nanrankdata

### ISSUE THREAD

**Issue by nils-braun** [danielhomola/boruta_py#8]
Thank you for your nice implementation of boruta!
However, I am wondering why you reimplemented the nanrankdata method of bottleneck. The reason I am wondering is that your new implementation can not handle cases, where the input data is in the form

X = [..., [nan, nan, nan], ...]

whereas the bottleneck.nanrankdata can (and this case occurs in my examples). I am sure there was a good reason to not use this method from bottleneck....

Thank you for your help!

**Comment by danielhomola** [comment]
Thanks for letting me know! I love bottleneck and use it all the time, but I also want to add Boruta to scikit-learn and they have a very strict dependency policy so I had to re-implement nansort with numpy/scipy. Do you have an idea how we could fix the issue you found?

Cheers,
d

**Comment by nils-braun** [comment]
Ah ok, now I understand why you switched from bottleneck to your implementation.
No, I do not have a quick fix in mind. I will think about it and answer, when I have found something.

Cheers
Nils
