### ISSUE TITLE
"TypeError: unhashable type" when calling feat_selector.fit(X,y) in the Madalon_Data_set.ipynb example

### ISSUE THREAD

**Issue by mhernandez1005** [danielhomola/boruta_py#9]
Hello,

I was able to pip install boruta no problem.
I then started stepping through the Madalon_Data_set ipython notebook.
When I get to feat_selector.fit(X,y), I received the following error:

TypeError: unhashable type

![madalon_data_set boruta_py error](https://cloud.githubusercontent.com/assets/7269142/16018669/b89f8e98-3162-11e6-91c2-8317fff422c4.PNG)

I am using python27, 32bit.
I have pandas-0.17

regards,

Manny

**Comment by danielhomola** [comment]
As pointed out in the 6th line of the example:
# NOTE BorutaPy accepts numpy arrays only, hence the .values attribute

I suspect you tried to use Boruta with a pandas DataFrame.

**Comment by mhernandez1005** [comment]
Thank you for the quick reply Daniel,

Yes, converting the pandas data frame to np array solved the error.

`feat_selector.fit(X.as_matrix(),y.as_matrix())`

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.as_matrix.html
